### ISSUE TITLE
blocked_transform is broken due to SYCL 2020 offset semantics

### ISSUE THREAD

**Issue by illuhad** [unisa-hpc/sycl-bench#72]
In SYCL 1.2.1, `accessor::operator[]` did not add the accessor offset. Users were instead expected to use `parallel_for` with offset to achieve correct indexing.

In SYCL 2020, `accessor::operator[]` does add the accessor offset. `parallel_for` offset is deprecated and should not be used.

The `blocked_transform` benchmark assumes the SYCL 1.2.1 semantics. Building it with a SYCL 2020 compiler causes the offset to be added twice, because the `parallel_for` is provided an offset, and additionally the `accessor::operator[]` now also adds the offset. So this benchmark is currently UB in any SYCL 2020 implementation.

We should change it to *not* use `parallel_for` with offset to make everything match again.

**Comment by Luigi-Crisci** [comment]
Are you referring to the `sycl2020` branch? We already removed the `parallel_for` offsets, but indeed the offset is added twice in the kernel. 
I'm going to fix it asap
