### ISSUE TITLE
`emitResults` has invalid memory accesses when used with `--warmup-run` & the first run fails

### ISSUE THREAD

**Issue by fodinabor** [unisa-hpc/sycl-bench#75]
`TimeMetricsProcessor::emitResults` leads to segfaults in case the very first benchmark run fails (e.g. doesn't verify), and just this run also happens to be the warmup run.
E.g. line `double median = resultsSeconds[resultsSeconds.size() / 2];` 

This is e.g. triggered by running `./nbody --size=1024 --local=256 --warmup-run` with AdaptiveCpp's `-DHIPSYCL_TARGETS=generic` as hierarchical parallel for isn't supported with this compilation-flow, yet.
In this case specifying `--no-verification` or leaving out `--warmup-run` works around the issue.

**Comment by Luigi-Crisci** [comment]
Looks like the warmup run is implemented just by skipping the first element of the result vector, but if the verification fails only the warmup run is present.
Working on a fix now.
