### ISSUE TITLE
Decide on future of sycl2020 branch - make default branch or merge into main?

### ISSUE THREAD

**Issue by illuhad** [unisa-hpc/sycl-bench#77]
It seems that currently people have difficulty finding the SYCL 2020 benchmarks because they live in the `sycl2020` branch which is not really mentioned anywhere.

We should consider
- Either making `sycl2020` the default branch
- or just merge it into `main` -- after all, it contains important functionality of this benchmark suite.

**Comment by Luigi-Crisci** [comment]
I think it makes sense to just merge it into the `main`. Me and @lorenzo-carpentieri were working on that (there are still some changes to be merged in the `sycl2020` branch), but we had to slow down to meet some other deadlines :).
I will try to submit a PR before my IWOCL talk.

**Comment by Luigi-Crisci** [comment]
#81 fixes this
